# Generated by Django 4.2.3 on 2023-09-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="doctor_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dr_name", models.CharField(max_length=200)),
                ("dr_contact", models.CharField(max_length=15)),
                ("dr_photo", models.CharField(max_length=200)),
                ("dr_qualification", models.CharField(max_length=200)),
                ("dr_experince", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="patient_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("patient_contact", models.CharField(max_length=100)),
                ("patient_email", models.CharField(max_length=100)),
                ("patient_address", models.CharField(max_length=100)),
                ("patient_photo", models.CharField(max_length=200)),
                ("pswrd", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="specialization_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sp_name", models.CharField(max_length=100)),
                ("sp_discription", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="patient_reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_report_name", models.CharField(max_length=200)),
                ("report_file", models.CharField(max_length=200)),
                ("report_date", models.CharField(max_length=100)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appoinmentsystem.patient_details",
                    ),
                ),
                (
                    "refferd_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appoinmentsystem.doctor_details",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor_details",
            name="dr_specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="appoinmentsystem.specialization_details",
            ),
        ),
        migrations.CreateModel(
            name="appoinmentscheduel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appoinment_date", models.CharField(max_length=100)),
                ("appoinment_day", models.CharField(max_length=200)),
                ("hours_minutes", models.CharField(default="", max_length=200)),
                ("appoinment_status", models.CharField(max_length=100)),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appoinmentsystem.doctor_details",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appoinmentsystem.patient_details",
                    ),
                ),
            ],
        ),
    ]
