# Generated by Django 4.2.3 on 2023-09-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appoinmentsystem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appoinmentscheduel",
            name="appoinment_date",
        ),
        migrations.RemoveField(
            model_name="appoinmentscheduel",
            name="patient_id",
        ),
    ]
