# Generated by Django 4.2.3 on 2023-09-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appoinmentsystem", "0002_remove_appoinmentscheduel_appoinment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor_details",
            name="dr_photo",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="drimages/"
            ),
        ),
    ]
