# Generated by Django 4.2.3 on 2023-09-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appoinmentsystem", "0004_alter_patient_details_patient_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="appointement_req",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appoinment_day", models.CharField(max_length=200)),
                ("hours_minutes", models.CharField(default="", max_length=200)),
                ("appoinment_status", models.CharField(max_length=100)),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appoinmentsystem.doctor_details",
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appoinmentsystem.patient_details",
                    ),
                ),
            ],
        ),
    ]
