# Generated by Django 4.2.3 on 2023-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appoinmentsystem", "0005_appointement_req"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
